/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

module derelict.vulkan.system.posix.wayland;
version (VK_USE_PLATFORM_WAYLAND_KHR):
extern(System):

public {
  import derelict.vulkan.base;
  import derelict.vulkan.types;
}

// TODO: add import of data related to Wayland protocol
// #include <wayland-client.h>
enum VK_KHR_wayland_surface = 1;
enum VK_KHR_WAYLAND_SURFACE_SPEC_VERSION   = 5;
enum VK_KHR_WAYLAND_SURFACE_EXTENSION_NAME = "VK_KHR_wayland_surface";

alias VkWaylandSurfaceCreateFlagsKHR = VkFlags;

struct VkWaylandSurfaceCreateInfoKHR {
  VkStructureType                sType  ;
  const(void)*                   pNext  ;
  VkWaylandSurfaceCreateFlagsKHR flags  ;
  wl_display*                    display;
  wl_surface*                    surface;
}

alias PFN_vkCreateWaylandSurfaceKHR = nothrow 
    VkResult function( VkInstance                            instance
                     , const(VkWaylandSurfaceCreateInfoKHR)* pCreateInfo
                     , const(VkAllocationCallbacks)*         pAllocator
                     , VkSurfaceKHR*                         pSurface );
alias PFN_vkGetPhysicalDeviceWaylandPresentationSupportKHR = nothrow 
    VkBool32 function( VkPhysicalDevice physicalDevice
                     , uint             queueFamilyIndex
                     , wl_display*      display );

mixin template WaylandFunctions() {
  PFN_vkCreateWaylandSurfaceKHR                        vkCreateWaylandSurfaceKHR;
  PFN_vkGetPhysicalDeviceWaylandPresentationSupportKHR vkGetPhysicalDeviceWaylandPresentationSupportKHR;
  pragma(inline, true)
  void bindFunctionsWayland(alias bind)() {
    bind(cast(void**)&vkCreateWaylandSurfaceKHR, "vkCreateWaylandSurfaceKHR");
    bind( cast(void**)&vkGetPhysicalDeviceWaylandPresentationSupportKHR
        , "vkGetPhysicalDeviceWaylandPresentationSupportKHR" );
  }
}

version (none) {
  VkResult vkCreateWaylandSurfaceKHR( VkInstance                            instance
                                    , const(VkWaylandSurfaceCreateInfoKHR)* pCreateInfo
                                    , const(VkAllocationCallbacks)*         pAllocator
                                    , VkSurfaceKHR*                         pSurface );
  VkBool32 vkGetPhysicalDeviceWaylandPresentationSupportKHR( VkPhysicalDevice physicalDevice
                                                           , uint             queueFamilyIndex
                                                           , wl_display*      display );
}