/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

module derelict.vulkan.system.windows;
version(Windows):
extern(System):

public {
  import derelict.vulkan.base;
  import derelict.vulkan.types;
}
import core.sys.windows.windows;

enum libNames = "vulkan-1.dll";
enum VK_KHR_win32_surface = 1;
enum VK_KHR_WIN32_SURFACE_SPEC_VERSION   = 5;
enum VK_KHR_WIN32_SURFACE_EXTENSION_NAME = "VK_KHR_win32_surface";

alias VkWin32SurfaceCreateFlagsKHR = VkFlags;

struct VkWin32SurfaceCreateInfoKHR {
  VkStructureType              sType    ;
  const(void)*                 pNext    ;
  VkWin32SurfaceCreateFlagsKHR flags    ;
  HINSTANCE                    hinstance;
  HWND                         hwnd     ;
}

alias PFN_vkCreateWin32SurfaceKHR = nothrow 
    VkResult function( VkInstance                          instance
                     , const(VkWin32SurfaceCreateInfoKHR)* pCreateInfo
                     , const(VkAllocationCallbacks)*       pAllocator
                     , VkSurfaceKHR*                       pSurface );
alias PFN_vkGetPhysicalDeviceWin32PresentationSupportKHR = nothrow 
    VkBool32 function( VkPhysicalDevice physicalDevice, uint queueFamilyIndex );

mixin template Functions() {
  PFN_vkCreateWin32SurfaceKHR                        vkCreateWin32SurfaceKHR;
  PFN_vkGetPhysicalDeviceWin32PresentationSupportKHR vkGetPhysicalDeviceWin32PresentationSupportKHR;
  pragma(inline, true)
  void bindFunctions(alias bind)() {
    bind(cast(void**)&vkCreateWin32SurfaceKHR, "vkCreateWin32SurfaceKHR");
    bind( cast(void**)&vkGetPhysicalDeviceWin32PresentationSupportKHR
        , "vkGetPhysicalDeviceWin32PresentationSupportKHR");
  }
}

version (none) {
  VkResult vkCreateWin32SurfaceKHR( VkInstance                          instance
                                  , const(VkWin32SurfaceCreateInfoKHR)* pCreateInfo
                                  , const(VkAllocationCallbacks)*       pAllocator
                                  , VkSurfaceKHR*                       pSurface );
  VkBool32 vkGetPhysicalDeviceWin32PresentationSupportKHR( VkPhysicalDevice physicalDevice, uint queueFamilyIndex );
}
